### ISSUE TITLE
Add functional tests for Spectacle plugin

### ISSUE THREAD

**Issue by johnboyes** [getgauge/gauge-tests#48]
It would be valuable to add some basic functional tests for the [Spectacle plugin][1].  It would then be straightforward (in a subsequent pull request on the Spectacle repo) to trigger these tests via a [GitHub Action][2] on every push and pull request in the Spectacle repo, giving valuable regression coverage.

The gauge-tests repo provides a powerful launchpad for adding functional tests for plugins, so having some basic Spectacle functional tests would also serve as a useful example for anyone writing a new plugin.  To that end, it would
also be useful to make this gauge-tests repo a [template repository][3], so that anyone writing a new Gauge plugin can easily use it as a starting template for adding their own functional tests.

[1]: https://github.com/getgauge/spectacle
[2]: https://github.com/features/actions
[3]: https://github.blog/2019-06-06-generate-new-repositories-with-repository-templates/

**Comment by johnboyes** [comment]
Created #49 to implement this

**Comment by zabil** [comment]
@johnboyes thanks a lot for raising this and working on a pull request!

However, it's best to keep the Gauge tests to only testing langauge runners. Tests could be added to https://github.com/getgauge/spectacle instead. Spectacle is written in golang and it should be easy to set up one.

I hope that's ok. Please do feel free to reach out for help.

**Comment by johnboyes** [comment]
Thanks for the reply, @zabil

> However, it's best to keep the Gauge tests to only testing langauge runners.

Fair enough, I can see your reasoning there.  Having said that,  I think that setting up end to end black box tests is still a fair amount of work, in any language.

So as above, I'd like to propose that you make this gauge-tests a [template repository](https://github.blog/2019-06-06-generate-new-repositories-with-repository-templates/), please - I see benefits to that and no downside, especially as it's a 5 minute job.  It would give anyone writing a new plugin a quick way to get end to end tests in place for their plugin.   For example, that would make it simple to create a spectacle-tests repo for the end to end tests, based on the gauge-tests repo.  Sound ok?

ps I also think it would be useful to make Spectacle a template repository too, as it's an excellent starting point for writing other documentation plugins (I'm currently spiking two new plugins to export Gauge specs to Confluence and Jira).  Let me know what you think, thanks.

**Comment by zabil** [comment]
> So as above, I'd like to propose that you make this gauge-tests a template repository, please - I see benefits to that and no downside, especially as it's a 5 minute job. This doesn't require accepting my PR, btw. It would give anyone writing a new plugin a quick way to get end to end tests in place for their plugin.

This is a good idea and I've done that.

> For example, that would make it simple to create a spectacle-functional-tests repo for the end to end tests, using gauge-tests as the template. Sound ok?

This makes sense too. I think it will be good to build on the template repo for the spectacle plugin and configure it as an github action for the main spectacle repo.

**Comment by zabil** [comment]
> ps I also think it would be useful to make the Spectacle repo a template repository too, as it's an excellent starting point for writing other documentation plugins (I'm currently spiking two new plugins to export Gauge specs to Confluence and Jira). Let me know what you think, thanks.

Done

**Comment by johnboyes** [comment]
Excellent, thanks for doing that so quickly.  I'll create a spectacle-functional-tests repo now and then close my PR with a comment linking to that repo, cheers.

**Comment by johnboyes** [comment]
I've created the [spectacle-functional-tests repo](https://github.com/agilepathway/spectacle-functional-tests), along with a [PR](https://github.com/agilepathway/spectacle-functional-tests/pull/1) to add the  Spectacle functional tests - very grateful if you can have a look, @zabil.

I've also created the GitHub Action workflow on my fork of the Spectacle repo, with the following code:

```
name: functional-tests
on: [push, pull_request]
jobs:

  functional-tests:
    name: FTs ubuntu-latest
    runs-on: ubuntu-latest
    strategy:
      matrix:
       include:
         - language: java
           task: spectacleJavaFT
         - language: js
           task: spectacleJsFT
         - language: dotnet
           task: spectacleDotnetFT
         - language: ruby
           task: spectacleRubyFT
         - language: python
           task: spectaclePythonFT
    steps:
      - name: Set up Go 1.15
        uses: actions/setup-go@v1
        with:
          go-version: 1.15
        id: go

      - name: Check out code
        uses: actions/checkout@v2

      - name: Install Gauge
        run: curl -SsL https://downloads.gauge.org/stable | sh

      - name: Install spectacle
        run: |
          go run build/make.go && go run build/make.go --distro
          gauge install spectacle --file $(ls -d bin/distros/*.zip)

      - name: Clone spectacle-functional-tests
        run: git clone --branch add-spectacle-tests https://github.com/agilepathway/spectacle-functional-tests

      - name: Run ${{ matrix.language }} FTs
        run: |
          gauge install ${{ matrix.language }}
          cd spectacle-functional-tests
          ./gradlew clean ${{ matrix.task }}

      - name: Upload logs
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: ft-logs-ubuntu-latest
          path: spectacle-functional-tests/logs

```

If you like what you see, I propose the following final steps if you agree:

1. we transfer the `spectacle-functional-tests` repo into the `getgauge` org
2. I submit a PR on the `spectacle` repo with the new GitHub Action functional tests workflow

**Comment by johnboyes** [comment]
Hi @zabil, very grateful if you could let me know what you think of my last comment above, please?  Thanks very much.

**Comment by zabil** [comment]
Sorry, for the delay. I took a look at the tests and forgot to respond. Here are my thoughts.

Since the spectacle plugin is a documentation plugin, it needs to have funtional tests only specific to testing the spectable report feature.

However I noticed that https://github.com/agilepathway/spectacle-functional-tests has all langauge plugin related functional tests too. For example https://github.com/agilepathway/spectacle-functional-tests/blob/master/specs/project_initialization.spec is not related to testing spectacle. 

I think it's would be better to have the functional tests specific to testing spectacle and the GitHub actions to run those functional tests in the main repo which is https://github.com/getgauge/spectacle you could create a `functional-tests` folder.

This way anyone who wants to write a documentation plugin can clone the repo refer to the tests and well as the GitHub actions if they want to make a release.

You can use just gauge java with gradle for these tests. So the github actions, the functional tests are all in one place which is https://github.com/getgauge/spectacle

Once that is done the github actions the spectacle repo will look like

```
name: functional-tests
on: [push, pull_request]
jobs:

  functional-tests:
    name: FTs ubuntu-latest
    runs-on: ubuntu-latest # needs to test for windows and mac os also
    steps:
      - name: Set up Go 1.15
        uses: actions/setup-go@v1
        with:
          go-version: 1.15
        id: go

      - name: Check out code
        uses: actions/checkout@v2

      - name: Install Gauge
        uses: getgauge/setup-gauge@master
        with:
          gauge-version: master
          gauge-plugins: java, html-report, screenshot

      - name: Install spectacle
        run: |
          go run build/make.go && go run build/make.go --distro
          gauge install spectacle --file $(ls -d bin/distros/*.zip)

  
       - name: Run ${{ matrix.language }} FTs
        run: |
          cd functional-tests
          ./gradlew clean ${{ matrix.task }}

      - name: Upload logs
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: ft-logs-ubuntu-latest
          path: functional-tests/logs

```
